### ISSUE TITLE
Dollycam: Frozen Cinematic Support

### ISSUE THREAD

**Issue by reallyluckyy** [reallyluckyy/IWXMVM#121]
There is currently no way to make cinematics where none of the players move, but the camera does. This should be possible!

**From discord:**
> Did some thinking about how frozen dollycam could work:
> - the camera tab could contain a checkbox "enable frozen cinematic"
> - if checked, we simulate the tick increasing if the demo is not paused, by returning some fake value from GetDemoInfo or so (could think about consolidating this into some other call so its not as misleading)
> - if checked, we have to ensure skip forward/backward dont do anything
> - if checked, we need to ensure CalculatePlaybackDelta always returns 0

**Comment by Caball009** [comment]
Feature has been implemented in v4.0.0.
